### Успешное создание проекта через Телеграмм бота -  201 Created (Ошибка 409: Дубликат проекта - запустите дважды для проверки)
# added_timestamp передастся в response как нынешнее значение,даже если на вход придет другой added_timestamp
POST http://localhost:8084/api/project/internal/project
Content-Type: application/json

{
  "author_telegram_user_id": 123,
  "github_repository_url": "https://github.com/zhukovsd/hangman",
  "programming_language": "Java",
  "roadmap_project": "HANGMAN",
  "telegram_user_id": 124551251,
  "telegram_username": "zhukovsd",
  "project_source_type": "TELEGRAM_BOT"
}

### Успешное создание проекта через Data-Importer -  201 Created (Ошибка 409: Дубликат проекта - запустите дважды для проверки)
POST http://localhost:8084/api/project/internal/project
Content-Type: application/json

{
  "author_telegram_user_id": 123,
  "github_repository_url": "https://github.com/zhukovsd/hangman",
  "programming_language": "Java",
  "roadmap_project": "HANGMAN",
  "telegram_user_id": 124551251,
  "telegram_username": "zhukovsd",
  "added_timestamp": 1765628000,
  "project_source_type": "DATA_IMPORTER"
}


### Ошибка 400: Пустое обязательное поле
POST http://localhost:8084/api/project/internal/project
Content-Type: application/json

{
  "author_telegram_user_id": 123,
  "github_repository_url": "not-a-url",
  "programming_language": "Java",
  "roadmap_project": "SIMULATION",
  "telegram_user_id": 124551251,
  "telegram_username": "zhukovsd",
  "project_source_type": "TELEGRAM_BOT"
}

### Ошибка 400: Отсутствует author_telegram_user_id
POST http://localhost:8084/api/project/internal/project
Content-Type: application/json

{
  "github_repository_url": "https://github.com/zhukovsd/simulation-test-3",
  "programming_language": "Java",
  "roadmap_project": "SIMULATION",
  "telegram_user_id": 124551251,
  "telegram_username": "zhukovsd",
  "project_source_type": "TELEGRAM_BOT"
}

###Ошибка 400: Неверный project_source_type
POST http://localhost:8084/api/project/internal/project
Content-Type: application/json

{
  "author_telegram_user_id": 123,
  "github_repository_url": "https://github.com/zhukovsd/hangman",
  "programming_language": "Java",
  "roadmap_project": "HANGMAN",
  "telegram_user_id": 124551251,
  "telegram_username": "zhukovsd",
  "project_source_type": "INVALID_TYPE"
}

###Ошибка 400: Неизвестный тип проекта
POST http://localhost:8084/api/project/internal/project
Content-Type: application/json

{
  "author_telegram_user_id": 123,
  "github_repository_url": "https://github.com/zhukovsd/unknown-project",
  "programming_language": "Java",
  "roadmap_project": "UNKNOWN-PROJECT",
  "telegram_user_id": 124551251,
  "telegram_username": "zhukovsd",
  "project_source_type": "TELEGRAM_BOT"
}
