spring:
  config:
    activate:
      on-profile: local-stack

  datasource:
    url: jdbc:postgresql://database:5432/it_mentor_community_platform?currentSchema=project_service
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092

kafka:
  topic:
    projects-project-created: projects.project.created
    notifications-students-review-submitted: notifications.students.review.submitted