spring:
  config:
    activate:
      on-profile: staging

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG}
      ssl.truststore.type: ${KAFKA_SSL_TRUSTSTORE_TYPE}
      ssl.truststore.location: ${KAFKA_SSL_TRUSTSTORE_LOCATION}

kafka:
  topic:
    projects-project-created: staging.projects.project.created
